repo_url: https://xinxukong.github.io/F-Droid/fdroid/repo
repo_name: xinxuxlkong的个人F-Droid仓库
repo_description: xinxukong的个人F-Droid仓库，自动同步Kazumi等应用。
archive_older: 0
keystore: keystore.p12
repo_keyalias: xinxukong
keydname: CN=xinxukong, OU=fdroid, O=xinxukong, L=Unknown, ST=Unknown, C=CN
